### ISSUE TITLE
Currency Cop not able to find maps in then new map stash

### ISSUE THREAD

**Issue by JYshadow** [currency-cop/currency-cop#18]
It can find maps in every other tab.

**Comment by benjy3gg** [comment]
The problem is on GGG's side.
If you try to access the map stash online (click on the profile picture) you wont see any maps either.
<img width="966" alt="screen shot 2018-01-11 at 15 16 23" src="https://user-images.githubusercontent.com/458675/34829893-73170832-f6e2-11e7-8453-94e95db27084.png">

The response to this request is:
`{"numTabs":22,"items":[]}`
