### ISSUE TITLE
Remove/Replace material-ui

### ISSUE THREAD

**Issue by nijikokun** [currency-cop/currency-cop#6]
It slows down development

**Comment by timrnz** [comment]
I'm interested in this, why does it slow down development?

**Comment by nijikokun** [comment]
Few reasons:

1. Size, includes entirety of `lodash` and more code than is necessary.
2. Styling, having to extend components, or drive them through a JSON configuration object is a pain, much easier to style elements using css classes in a stylesheet and much better separation of concerns.
3. Overload, when dealing with the component you come across the scenario of "can I do this", when you can't you have the "what will it take to make it do this", happens often.
4. Updates, it's been in "beta" for quite some time, and there are build quirks that you can't configure such as preventing the compression of class names at build in prod. To get around this currently I custom patch the library.

It's a multitude rather than a single thing.

**Comment by dhuber666** [comment]
Hi guys my first message in a opensource issue ever. 
So that basically means we should get rid of materialize and code our own Styling aka CSS (Sass) ?

**Comment by timrnz** [comment]
Hi @dhuber666 welcome to Open Source my friend.

The [material-ui project](http://www.material-ui.com/#/) is a full blown component library which includes a decent amount of JS components to help you build applications.

By removing the project entirely, it free's projects like this one up from the constraints provided by the host library. That being said, this project would either need to choose another replacement library if they want to get things for "free", but potentially suffer the downsides introduced by the library, or roll their own.

It's not unfair to roll their own, but does mean you typically spend time on building common components that could otherwise be easily solved with importing a library such as material-ui.

As far as rolling his own CSS, again not strictly true, @nijikokun could choose to pick up just the CSS from the material project directly and roll his own set of components on top if he wants to.

So ultimately, it's worth looking at the core project, what it provides, and how much value you're willing to trade when it comes to getting started vs doing all the extra work around rolling your own core sets.

**Comment by nijikokun** [comment]
Welcome @dhuber666, and thanks for the summary @timrnz.

To address your question specifically, I would recommend going with what the project _currently_ has implemented.

In other news related to this topic, I have started doing what @timrnz said:

1. Removed `material-ui` locally
2. Imported a `flexbox` grid
3. Implemented some basic components in their own file: `Button`, `PrimaryButton`, `Input`
4. Exported out the "classes" / "helpers" / "api" into their own files

I'll continue down this road, as it is speeding up development and slimming down the actual html. No more inline css, less attributes to memorize, and faster to iterate on.

On a side note, doing the above has already dropped down the core file to around `1800` lines. Now to export the "view" components out ;)
