### ISSUE TITLE
Newest Currency Cop(2.0.0-beta.12) detected as Malware by Avast?

### ISSUE THREAD

**Issue by Leoguy77** [currency-cop/currency-cop#70]
Hey guys,

i downloaded the newest Currency Cop update like 5 minutes ago and it got auto´automatically deleted by avast. 
In order to test if the problem occurs on other anti virus softwares too, i uploaded the newest installer .exe from 2.0.0-beta.12 to virustotal: https://www.virustotal.com/de/file/6c71c2faf1d7546e0a6a63992461c7356f641ea73d0c93da6840e45e46a54162/analysis/1530110763/

6/64 detections . among those are Avast, AVG and Kaspersky.

@nijikokun

**Comment by nijikokun** [comment]
Yep, not much I can do outside paying 200$ a year for a cert.

**Comment by Leoguy77** [comment]
the ones before didnt got getected @nijikokun

**Comment by nijikokun** [comment]
Could you upload to a non-germanic site? It states cert issues there, nothing changed in .12 that warrants such an issue.

**Comment by nijikokun** [comment]
Unless they consider timsort algorithms malware.

**Comment by nijikokun** [comment]
Currently getting only 3 types:

https://www.virustotal.com/#/file/6c71c2faf1d7546e0a6a63992461c7356f641ea73d0c93da6840e45e46a54162/detection

- **FileRepMalware** - Low reputation in these applications (false-positive, over-aggressive matching)
- **HW32.Packed.20F8** - False positive, compression (https://www.reddit.com/r/qBittorrent/comments/89n5bx/virus_total_detected_this_engine/)
- **not-a-virus:HEUR:AdWare.Win32.Agent.gen** - False positive, no advertisements see (https://www.kaspersky.com/blog/not-a-virus/18015/)

**Comment by nijikokun** [comment]
I've applied to the whitelist program for Kaspersky, however, since I don't pay for a root approved and generate my own cert I believe they will deny.

<img width="999" alt="screen shot 2018-06-28 at 3 59 27 pm" src="https://user-images.githubusercontent.com/198276/42064752-5c9eccd2-7aec-11e8-8067-1534e05d007b.png">

I've also applied to the Avast, however not sure what will happen there:

<img width="1121" alt="screen shot 2018-06-28 at 4 05 19 pm" src="https://user-images.githubusercontent.com/198276/42064929-1e3aa8c0-7aed-11e8-81e1-03a1c2375ec9.png">

These are false positives and not much I can really do about it.

**Comment by nijikokun** [comment]
> Please note that "not-a-virus" notification is informative and do not classify a software as malicious. If users install it on their own initiative, then the "not-a-virus" notification should not affect their decision to install/use the software.

**Comment by Leoguy77** [comment]
thats right mate. but it got auto-deleted by avast on download for me :/

**Comment by nijikokun** [comment]
That is the official response from Avast, I will respond with your complaint
