### ISSUE TITLE
failure when opening currency-cop since latest patch?

### ISSUE THREAD

**Issue by nerdc0re-net** [currency-cop/currency-cop#84]
This is fine: Failed to obtain currency item rates for Incursion Event (IRE001) league.

**Comment by templar-guard** [comment]
Me too, have you found the solution?

**Comment by Grimka** [comment]
Hello there, same issue for everyone I guess..
I forked the repo, digged into the code and I've made a little patch just now, it's because event leagues hasn't started yet and the app is trying to gather item data/price from it which return errors.

I changed this :
```
let leagues = await CC.Api.getLeagues();
await this.setState({ leagues });
```

To this : 

```
let leagues = await CC.Api.getLeagues();
leagues = this.filterNotStartedLeagues(leagues);
await this.setState({ leagues });

filterNotStartedLeagues (leagues) {
  let actualDate = new Date();
  leagues = leagues.filter(function(league){
    return(new Date(league.startAt) <= actualDate);
  });

  return leagues;
}
```

I've made a pull request, if the dev come around he should be able to add the hotfix

The issue should also fix itself when event leagues will start, making item/price requests functionnal again.
